export const USER_LOADED = "USER_LOADED";
export const RELOADING_USER = "RELOADING_USER";
export const WALLET_CHANGE = "WALLET_CHANGE";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const VOLUME_CHANGED = "VOLUME_CHANGED";
export const SITE_SOUNDS_TOGGLED = "SITE_SOUNDS_TOGGLED";
export const GAME_SOUNDS_TOGGLED = "GAME_SOUNDS_TOGGLED";
export const NATURE_SOUNDS_TOGGLED = "NATURE_SOUNDS_TOGGLED";
export const CHAT_TOGGLED = "CHAT_TOGGLED";
